# Exercícios: Parte 07
O arquivo ```bmw.csv``` contem informações associadas a venda de de veículos usados da marca BMW no Reino Unido. Utilizando comandos de filtro de texto e agrupamento, gere as informações listadas a seguir:
1. Qual o preço (_price_) médio dos modelos (_model_) _Series_ (i.e. 1 _Series_, 2 _Series_, ...)? (utilize o comando ```str.contains()```)
2. Represente a distribuição de frequência dos preços somentes para os modelos Series.
3. Gere as estatísticas descritivas dos preços, agrupando por tipo de transmissão (_transmission_).
4. Gere as estatísticas descritivas dos preços, agrupando por modelo.
5. Gere a mesma informação anterior somente para os modelos Series, agrupando também pelo tipo de transmissão.
6. Descubra qual o modelo e ano que possui mais veículos a venda, indicando o preço médio para essa categoria.

In [1]:
import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv('https://raw.githubusercontent.com/ronaldolagepessoa/data_science/master/dados/bmw.csv')
df.head()

,model,year,price,transmission,mileage,fuelType,tax,mpg,engineSize
0,5 Series,2014,11200,Automatic,67068,Diesel,125,57.6,2.0
1,6 Series,2018,27000,Automatic,14827,Petrol,145,42.8,2.0
2,5 Series,2016,16000,Automatic,62794,Diesel,160,51.4,3.0
3,1 Series,2017,12750,Automatic,26676,Diesel,145,72.4,1.5
4,7 Series,2014,14500,Automatic,39554,Diesel,160,50.4,3.0