# Exercícios: Parte 06
O arquivo ```AB_NYC_2019.csv``` contem informações sobre reservas de espaços no AirBnB de Nova Iorque.
Com base no ```DataFrame```criado a partir deste arquivo, responda o seguinte:
1. Quais colunas possuem pelo menos um registro em branco?
2. Elimine as linhas que possuam pelo menos um registro em branco.
3. Quais colunas poderiam ser eliminadas por não oferecerem informações relevantes a uma análise estatística? (Dica: utilize o comando [```Series.nunique()```](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.nunique.html) para contar o número de valores que não se repetem).
4. Elimine as colunas identificadas na etapa anterior utilizando o comando [```DataFrame.drop(lista_de_colunas, axis=1, inplace=True)```](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.drop.html).
5. Modifique a tipagem das colunas para reduzir o uso de memória.

In [2]:
import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv('https://raw.githubusercontent.com/ronaldolagepessoa/data_science/master/dados/AB_NYC_2019.csv')
df.head()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,2539,Clean & quiet apt home by the park,2787,John,Brooklyn,Kensington,40.64749,-73.97237,Private room,149,1,9,2018-10-19,0.21,6,365
1,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,225,1,45,2019-05-21,0.38,2,355
2,3647,THE VILLAGE OF HARLEM....NEW YORK !,4632,Elisabeth,Manhattan,Harlem,40.80902,-73.94190,Private room,150,3,0,NaN,NaN,1,365
3,3831,Cozy Entire Floor of Brownstone,4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514,-73.95976,Entire home/apt,89,1,270,2019-07-05,4.64,1,194
4,5022,Entire Apt: Spacious Studio/Loft by central park,7192,Laura,Manhattan,East Harlem,40.79851,-73.94399,Entire home/apt,80,10,9,2018-11-19,0.10,1,0