In [2]:
import pandas as pd
import seaborn as sns

df = pd.read_csv('dados/bmw.csv')
df.head()

,model,year,price,transmission,mileage,fuelType,tax,mpg,engineSize
0,5 Series,2014,11200,Automatic,67068,Diesel,125,57.6,2.0
1,6 Series,2018,27000,Automatic,14827,Petrol,145,42.8,2.0
2,5 Series,2016,16000,Automatic,62794,Diesel,160,51.4,3.0
3,1 Series,2017,12750,Automatic,26676,Diesel,145,72.4,1.5
4,7 Series,2014,14500,Automatic,39554,Diesel,160,50.4,3.0

In [5]:
df.groupby(['model', 'transmission', 'year']).price.describe().sort_values('mean', ascending=False)

                             count          mean           std      min  \
model     transmission year
 X7       Semi-Auto    2020   13.0  71921.923077   5961.543487  63990.0
 M5       Automatic    2019    7.0  70957.285714   2478.426968  68850.0
 X7       Semi-Auto    2019   25.0  69678.840000   4712.437477  61875.0
 M5       Semi-Auto    2019   11.0  69124.272727   9309.032357  58991.0
 X7       Automatic    2019   16.0  68588.000000   4869.759049  59988.0
 i8       Automatic    2019    6.0  68527.666667   3859.302614  64750.0
 X7       Automatic    2020    1.0  66988.000000           NaN  66988.0
 8 Series Semi-Auto    2020   12.0  64867.750000   6889.121281  56990.0
                       2018    1.0  63980.000000           NaN  63980.0
 M5       Automatic    2018    2.0  63870.000000   2938.735783  61792.0
 8 Series Automatic    2019    8.0  63821.125000   5855.505283  55980.0
          Semi-Auto    2019   18.0  63497.333333  10421.836549  51980.0
 M3       Semi-Auto    2019    1.0  62995.000000           NaN  62995.0
 M4       Automatic    2016    4.0  62355.750000  31689.286606  32983.0
 X6       Semi-Auto    2019   22.0  60248.227273   6559.123329  41780.0
 M5       Semi-Auto    2018    1.0  59973.000000           NaN  59973.0
 i8       Automatic    2018    3.0  59445.000000   4939.557166  55485.0
 X5       Automatic    2020    2.0  58991.500000   7076.017559  53988.0
 X6       Semi-Auto    2020   15.0  58234.000000   5527.662487  49975.0
          Automatic    2019   12.0  57113.250000   7865.637385  40980.0
 X5       Semi-Auto    2020   16.0  56856.375000   6290.201818  44875.0
 X6       Automatic    2020    1.0  56000.000000           NaN  56000.0
 7 Series Semi-Auto    2020    6.0  54743.000000   1883.469033  52999.0
 M3       Automatic    2017    1.0  53995.000000           NaN  53995.0
 i8       Automatic    2017    3.0  53781.000000   5637.111228  48898.0
 7 Series Automatic    2019   10.0  50740.600000   3244.981637  45640.0
 X5       Semi-Auto    2019  145.0  50634.993103   4507.851198  43750.0
 M4       Semi-Auto    2020   16.0  50437.437500   4770.874720  43000.0
 X5       Automatic    2019   75.0  49333.280000   5438.581104  43500.0
          Semi-Auto    2018    3.0  49161.333333   3689.921454  44990.0
...                            ...           ...           ...      ...
 1 Series Manual       2010    7.0   4863.571429   1454.337519   2450.0
                       2008    7.0   4553.428571   1417.329867   2999.0
 5 Series Automatic    2007    2.0   4484.500000   2807.921028   2499.0
 3 Series Manual       2007    4.0   4305.000000   3036.777349   2375.0
 5 Series Automatic    2002    2.0   4292.500000   3814.841085   1595.0
                       2006    1.0   4290.000000           NaN   4290.0
                       2004    1.0   4250.000000           NaN   4250.0
 1 Series Manual       2009    4.0   4193.750000    962.118972   2995.0
 3 Series Automatic    2002    1.0   3999.000000           NaN   3999.0
 5 Series Manual       2007    1.0   3995.000000           NaN   3995.0
 Z3       Manual       1999    3.0   3980.000000     25.980762   3950.0
                       1997    1.0   3950.000000           NaN   3950.0
                       1998    1.0   3950.000000           NaN   3950.0
 X3       Manual       2006    2.0   3847.000000    492.146320   3499.0
 1 Series Automatic    2005    1.0   3795.000000           NaN   3795.0
 Z4       Manual       2006    1.0   3595.000000           NaN   3595.0
 1 Series Automatic    2009    1.0   3500.000000           NaN   3500.0
 X3       Automatic    2004    1.0   3495.000000           NaN   3495.0
 Z4       Automatic    2003    1.0   3495.000000           NaN   3495.0
 3 Series Manual       2005    2.0   3437.000000   1326.532322   2499.0
          Automatic    2001    1.0   3050.000000           NaN   3050.0
 1 Series Manual       2006    2.0   2992.500000      3.535534   2990.0
 3 Series Manual       2004    3.0   2774.333333   1276.301819   1445.0
                       2002    2.0   2670.000000    452.548340   2350.0
                       2006    2.0   2647.500000    208.596500   2500.0
 1 Series Manual       2004    1.0   2495.000000           NaN   2495.0
 5 Series Manual       2000    1.0   1699.000000           NaN   1699.0
 3 Series Automatic    2000    1.0   1550.000000           NaN   1550.0
 1 Series Manual       2007    1.0   1500.000000           NaN   1500.0
 3 Series Automatic    1999    1.0   1200.000000           NaN   1200.0

                                  25%      50%       75%      max
model     transmission year
 X7       Semi-Auto    2020  64999.00  71980.0  77995.00  79566.0
 M5       Automatic    2019  69439.00  69995.0  71995.00  74988.0
 X7       Semi-Auto    2019  66000.00  68720.0  73950.00  77880.0
 M5       Semi-Auto    2019  62939.00  65000.0  71497.50  89900.0
 X7       Automatic    2019  65337.25  68442.0  70580.00  78386.0
 i8       Automatic    2019  65437.50  67720.0  70985.00  74226.0
 X7       Automatic    2020  66988.00  66988.0  66988.00  66988.0
 8 Series Semi-Auto    2020  59995.00  62495.0  67741.00  79991.0
                       2018  63980.00  63980.0  63980.00  63980.0
 M5       Automatic    2018  62831.00  63870.0  64909.00  65948.0
 8 Series Automatic    2019  59747.50  63400.5  66224.50  73900.0
          Semi-Auto    2019  56962.50  59742.0  66949.25  88980.0
 M3       Semi-Auto    2019  62995.00  62995.0  62995.00  62995.0
 M4       Automatic    2016  37870.75  58245.0  82730.00  99950.0
 X6       Semi-Auto    2019  56245.00  59992.5  64868.00  69993.0
 M5       Semi-Auto    2018  59973.00  59973.0  59973.00  59973.0
 i8       Automatic    2018  56677.50  57870.0  61425.00  64980.0
 X5       Automatic    2020  56489.75  58991.5  61493.25  63995.0
 X6       Semi-Auto    2020  55695.00  55995.0  59494.00  69995.0
          Automatic    2019  56215.00  58800.0  61156.25  66290.0
 X5       Semi-Auto    2020  52712.50  57130.0  62232.75  65000.0
 X6       Automatic    2020  56000.00  56000.0  56000.00  56000.0
 7 Series Semi-Auto    2020  53248.75  54495.0  55365.50  57980.0
 M3       Automatic    2017  53995.00  53995.0  53995.00  53995.0
 i8       Automatic    2017  50696.50  52495.0  56222.50  59950.0
 7 Series Automatic    2019  48235.00  50420.0  53450.00  55156.0
 X5       Semi-Auto    2019  47440.00  49990.0  52490.00  72990.0
 M4       Semi-Auto    2020  47987.50  49556.5  51100.50  59999.0
 X5       Automatic    2019  44941.50  48090.0  50940.00  73000.0
          Semi-Auto    2018  47742.50  50495.0  51247.00  51999.0
...                               ...      ...       ...      ...
 1 Series Manual       2010   4170.00   4995.0   5992.50   6275.0
                       2008   3957.50   3995.0   4745.00   7475.0
 5 Series Automatic    2007   3491.75   4484.5   5477.25   6470.0
 3 Series Manual       2007   2506.25   3022.5   4821.25   8800.0
 5 Series Automatic    2002   2943.75   4292.5   5641.25   6990.0
                       2006   4290.00   4290.0   4290.00   4290.0
                       2004   4250.00   4250.0   4250.00   4250.0
 1 Series Manual       2009   3745.00   4242.5   4691.25   5295.0
 3 Series Automatic    2002   3999.00   3999.0   3999.00   3999.0
 5 Series Manual       2007   3995.00   3995.0   3995.00   3995.0
 Z3       Manual       1999   3972.50   3995.0   3995.00   3995.0
                       1997   3950.00   3950.0   3950.00   3950.0
                       1998   3950.00   3950.0   3950.00   3950.0
 X3       Manual       2006   3673.00   3847.0   4021.00   4195.0
 1 Series Automatic    2005   3795.00   3795.0   3795.00   3795.0
 Z4       Manual       2006   3595.00   3595.0   3595.00   3595.0
 1 Series Automatic    2009   3500.00   3500.0   3500.00   3500.0
 X3       Automatic    2004   3495.00   3495.0   3495.00   3495.0
 Z4       Automatic    2003   3495.00   3495.0   3495.00   3495.0
 3 Series Manual       2005   2968.00   3437.0   3906.00   4375.0
          Automatic    2001   3050.00   3050.0   3050.00   3050.0
 1 Series Manual       2006   2991.25   2992.5   2993.75   2995.0
 3 Series Manual       2004   2166.50   2888.0   3439.00   3990.0
                       2002   2510.00   2670.0   2830.00   2990.0
                       2006   2573.75   2647.5   2721.25   2795.0
 1 Series Manual       2004   2495.00   2495.0   2495.00   2495.0
 5 Series Manual       2000   1699.00   1699.0   1699.00   1699.0
 3 Series Automatic    2000   1550.00   1550.0   1550.00   1550.0
 1 Series Manual       2007   1500.00   1500.0   1500.00   1500.0
 3 Series Automatic    1999   1200.00   1200.0   1200.00   1200.0

[420 rows x 8 columns]

In [3]:
import plotly.graph_objects as go
fig = go.Figure(data=go.Bar(y=[2, 3, 1]))
fig.write_html('first_figure.html', auto_open=True)

In [13]:
import plotly.express as px
import pandas as pd
# df = px.data.gapminder().query("year == 2007")
df = pd.read_csv('https://raw.githubusercontent.com/ronaldolagepessoa/data_science/master/dados/housing_ok.csv')
fig = px.density_mapbox(df, lat='latitude', lon='longitude', z='preco', radius=10,
                        center=dict(lat=0, lon=180), zoom=0,
                        mapbox_style="stamen-terrain")
fig.write_html('first_figure.html', auto_open=True)